# Generated by Django 2.1 on 2019-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20190425_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editor',
            field=models.ManyToManyField(to='modelo.Editor'),
        ),
    ]
