# Generated by Django 2.1 on 2019-05-22 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_libro_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editor',
        ),
        migrations.AddField(
            model_name='autor',
            name='login',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='pais',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AddField(
            model_name='post',
            name='autores',
            field=models.ManyToManyField(to='modelo.Autor'),
        ),
    ]
