# Generated by Django 2.1 on 2019-05-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20190522_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autores',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.Autor'),
            preserve_default=False,
        ),
    ]
